/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eason_helloffmpeg_MainActivity */

#ifndef _Included_com_eason_helloffmpeg_MainActivity
#define _Included_com_eason_helloffmpeg_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eason_helloffmpeg_MainActivity
 * Method:    avcodecInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eason_helloffmpeg_MainActivity_avcodecInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_eason_helloffmpeg_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eason_helloffmpeg_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_eason_helloffmpeg_MainActivity
 * Method:    avcodecConfiguration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eason_helloffmpeg_MainActivity_avcodecConfiguration
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
